import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

print("Loading model baseline output...")
# Load the data generated by baseline_kmeans.py which has Cluster_ID (k=8)
df = pd.read_parquet("data/gold/model_baseline_output.parquet")

# Features used for clustering (same as baseline_kmeans.py)
feature_cols = [
    "poi_total_catchment",
    "poi_driver_catchment",
    "poi_cannibal_risk",
    "Tuition_Weekend_Surge",
    "Tourist_Peak_Multiplier",
    "Sports_Big_Match_Spike",
    "Health_Catchment_Spike",
    "Number_of_Weekends",
    "Holiday_Count",
    "Has_High_Footfall_Catchment",
    "Has_Cannibalization_Risk"
]

print("Preprocessing and scaling...")
# We must aggregate to Outlet level since PCA is per outlet
outlet_df = df.groupby("Outlet_ID")[feature_cols].mean().fillna(0)

# Add the cluster ID (it should be the same for the outlet)
cluster_map = df.groupby("Outlet_ID")["Cluster_ID"].first()
outlet_df = outlet_df.join(cluster_map)

# Also get Total Volume to show bubble size or something (optional)
vol_map = df.groupby("Outlet_ID")["Total_Volume"].sum()
outlet_df = outlet_df.join(vol_map.rename("Total_Volume_Sum"))

scaler = StandardScaler()
X_scaled = scaler.fit_transform(outlet_df[feature_cols])

print("Running PCA...")
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

outlet_df["PCA1"] = X_pca[:, 0]
outlet_df["PCA2"] = X_pca[:, 1]

print("Plotting...")
plt.figure(figsize=(10, 6))

# We have 30 clusters, so using a qualitative colormap
scatter = sns.scatterplot(
    data=outlet_df,
    x="PCA1",
    y="PCA2",
    hue="Cluster_ID",
    palette="tab20",  # tab20 has 20 colors, will repeat but looks good
    s=20,
    alpha=0.7,
    edgecolor=None,
    legend=False # 30 clusters is too many for a legend
)

plt.title("2D PCA Projection of 30 Micro-Segment Clusters")
plt.xlabel(f"Principal Component 1 ({pca.explained_variance_ratio_[0]*100:.1f}%)")
plt.ylabel(f"Principal Component 2 ({pca.explained_variance_ratio_[1]*100:.1f}%)")

# Ensure output directory exists
out_dir = Path("reports/figures")
out_dir.mkdir(parents=True, exist_ok=True)

plt.tight_layout()
plt.savefig(out_dir / "cluster_pca.png", dpi=300)
print(f"Saved true PCA plot to {out_dir / 'cluster_pca.png'}")
